service: retoCulqui
custom:
  logger:
    level:
      dev: TRACE
      uat: DEBUG
      qas: INFO
      prd: INFO
plugins:
  - serverless-offline
  - serverless-plugin-typescript
provider:
  name: aws
  runtime: nodejs12.x
  stage: ${opt:stage,'dev'}
  region: us-east-1
  apiName: ${opt:stage, self:provider.stage}
  environment:
    DB_USER: ${file(${opt:stage, self:provider.stage}.config.yml):DB_USER}
    DB_PASS: ${file(${opt:stage, self:provider.stage}.config.yml):DB_PASS}
    DB_DBNAME: ${file(${opt:stage, self:provider.stage}.config.yml):DB_DBNAME}
    DB_CLUSTER: ${file(${opt:stage, self:provider.stage}.config.yml):DB_CLUSTER}
    AUTORIZATION: ${file(${opt:stage, self:provider.stage}.config.yml):AUTORIZATION}
package:
  exclude:
    - .build
    - .serverless
    - test/**
    - .eslintrc.json
    - package-lock.json
    - package.json

functions:
  createCreditCard:
    handler: src/controller/handler.createCreditCard
    events:
      - http:
          method: post
          path: /creditCard
          cors: true
  findCreditCard:
    handler: src/controller/handler.findCreditCard
    events:
      - http:
          path: /creditCard/{token}
          method: get
