service: retoCulqui
custom:
  logger:
    level:
      dev: TRACE
      uat: DEBUG
      qas: INFO
      prd: INFO
  # authorizer:
  #   arn: arn:aws:lambda:#{AWS::Region}:#{AWS::AccountId}:function:identity-api-${self:provider.stage}-authorizator
plugins:
  - serverless-offline
  - serverless-plugin-typescript
provider:
  name: aws
  runtime: nodejs12.x
  stage: ${opt:stage,'dev'}
  region: us-east-1
  apiName: ${opt:stage, self:provider.stage}
  environment:
    DB_CONN_STRING: ${file(${opt:stage, self:provider.stage}.config.yml):DB_CONN_STRING}
package:
  exclude:
    - .build
    - .serverless
    - test/**
    - .eslintrc.json
    - package-lock.json
    - package.json

functions:
  createCreditCard:
    handler: src/controller/handler.createCreditCard
    events:
      - http:
          method: post
          path: /creditCard
          cors: true
  findCreditCard:
    handler: src/controller/handler.findCreditCard
    events:
      - http:
          path: /creditCard/{token}
          method: get
          # authorizer:
          #   arn: '${self:custom.authorizer.arn}'
          #   identitySource: method.request.header.TOKEN
          #   type: request
